[package]
name = "ootle-payment-processor-storage-sqlite"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
ootle-payment-processor-storage = { workspace = true }
tari_template_lib = { workspace = true }

anyhow = { workspace = true }
thiserror = { workspace = true }
serde_json = { workspace = true }

[dependencies.sqlx]
version = "0.8.6"
default-features = false
features = ["any", "runtime-tokio", "macros", "sqlite", "migrate", "time", "json", "uuid"]